### ISSUE TITLE
"Community" channel in Yahoo screen not working

### ISSUE THREAD

**Issue by hzrimtrog** [plexinc-plugins/YahooScreen.bundle#5]
The "Community" channel in yahoo screen isn't working.  It throws an error.  Most of the other channels appear to be working well.

It is weird because that channel used to work when it was just previews for the new episodes, but then when the new episodes came out, those new episodes don't play.

**Comment by enlewof** [comment]
Looks like it works now mysteriously.

**Comment by hzrimtrog** [comment]
Indeed it does.  The birds must have left the nest at the server farm and all is well in the world.
